### ISSUE TITLE
operator names

### ISSUE THREAD

**Issue by petenicholls** [IBMStreams/streamsx.eventstore#1]
Operator name should contain indication of function provided.  For example EventStoreInsert is better than EventStoreSink.

**Comment by markheger** [comment]
Current toolkit version is 0.1, therefore it should be possible to rename `EventStoreSink` to `EventStoreInsert` for toolkit version 1.0 .

**Comment by markheger** [comment]
as discussed with @dzilio, the operator should not be renamed since some customer projects are using it.
